django_project_root/django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('products/', include('products.urls')),
    path('accounts/', include('allauth.urls')),
    path('store/', include('store.urls')),
    path('emails/', include('mail.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_project_root/mail/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('', EmailListView.as_view(), name='email_list'),
    path('update/<slug:pk>/', EmailUpdateView.as_view(), name='email_update'),
    path('create/', EmailCreateView.as_view(), name='create_email'),
    path('details/<slug:pk>/', EmailDetailView.as_view(), name='email_details'),
    path('email/confirm/send/<slug:pk>/', EmailConfirmSendView.as_view(), name='email_send_confirm'),
    path('email/delete/<slug:pk>/', EmailDeleteView.as_view(), name='delete_email'),
]

django_project_root/products/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    #PRODUCT MODEL VIEWS
    path('', ProductView.as_view(), name='products_list'),
    path('create/', ProductCreateView.as_view(), name='product_create'),
    path('update/<slug:pk>', ProductUpdateView.as_view(), name='product_update'),
    path('delete/<slug:pk>', ProductDeleteView.as_view(), name='product_delete'),
    path('product/detail/<slug:pk>/', ProductDetailView.as_view(), name='product_detail'),
    path('products/search/', ProductSearchView.as_view(), name='product_search_results'),
    #CATEGORIES MODEL VIEWS
    path('categories/', CategoriesListView.as_view(), name='category_list'),
    path('categories/create/', CategoriesCreateView.as_view(), name='category_create'),
    path('categories/update/<slug:pk>/', CategoriesUpdateView.as_view(), name='category_update'),
    path('categories/delete/<slug:pk>/', CategoriesDeleteView.as_view(),  name='category_delete'),
    #PRODUCTS BY CATEGORY
    path('categories/by_product/<str:category>/', ProductsByCategoryView.as_view(), name='product_by_category'),
    path('categories/products/update/<slug:pk>', ProductUpdateView.as_view(), name='products_by_cat_up'),
    #ORDERS MODEL VIEWS
    path('orders/', OrdersIncompleteListView.as_view(), name='orders_incomplete_list'),
    path('orders/history/', OrdersCompleteListView.as_view(), name='order_complete_list'),
    path('orders/order_items/<slug:pk>/', OrderItemsView.as_view(), name='order_items'),
    path('order/update/<slug:pk>/', OrderStatusChange.as_view(), name='order_update'),
    path('order/user/<slug:pk>/', OrderUserDetailView.as_view(), name='order_user_detail'),
    path('order/user/order-history/<slug:pk>/', CustomerOrderHistory.as_view(), name='user_order_history'),
    path('orders/search/', OrderSearchView.as_view(), name='order_search_results'),

    
]

django_project_root/products/models.py
from django.db import models
from django.db.models import Count

from django.contrib import messages

# Create your models here.

class Categories(models.Model):
    category_name = models.CharField(max_length=100, unique=True)
    description = models.TextField(max_length=300, blank=True)
    
    class Meta:
        verbose_name_plural = 'Categories'
    
    def __str__(self):
        return self.category_name

class Product(models.Model):
    BOOL_CHOICES = ((True, 'Display'), (False, 'Keep Hidden'))
    
    product_category = models.ForeignKey(Categories, on_delete=models.SET_NULL, null=True, related_name='categories', blank=True)
    title = models.CharField(max_length=100)
    image = models.ImageField(null=True, blank=True, upload_to='images/')
    description = models.TextField(max_length=250)
    price = models.DecimalField(max_digits=12, decimal_places=2)
    stock = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    display_product = models.BooleanField(null=True, default=False, choices=BOOL_CHOICES)
    id_hidden = models.IntegerField(default=0, null=True, blank=True)
    
    @property
    def stock_amount(self):
        if self.stock <= 0:
            return "This item is out of stock!"
        elif self.stock <= 10:
            return f'Hurry this item is almost out of stock! Only {self.stock} left.'
        else:
            return f"{self.stock} in stock"       
    
    @property 
    def imageURL(self):
        try:
            url = self.image.url
        except:
            url = ''
        return url
    
    class Meta:
        verbose_name_plural = 'Products'
        unique_together = ['title', 'product_category']
    
    def __str__(self):
        return str(self.product_category) + '-' + self.title

django_project_root/products/forms.py
from django import forms
from django.core.exceptions import ValidationError, NON_FIELD_ERRORS
from django.forms import HiddenInput

from store.models import Order
from .models import Product, Categories

#FORMS
class CategoriesForm(forms.ModelForm):
    class Meta:
        model = Categories
        fields = '__all__'
        
   
class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'
        error_messages = {
            NON_FIELD_ERRORS: {
                'unique_together': "Sorry, a product with this title already exists inside selected category."
            }
        }
        widgets = {'id_hidden': HiddenInput(),}
   

    def clean(self):
        cleaned_data = super().clean()
        stock_amount = self.cleaned_data.get('stock')
        display_value = self.cleaned_data.get('display_product')
        
        if stock_amount <= 0 and display_value == True:
            raise forms.ValidationError(('If you wish to display this value in your shop, it must be in stock.'), code='invalid')
        return cleaned_data    


class OrderUpdateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['complete', ]
       

django_project_root/products/views.py
from typing import Any, Dict
from django.db.models.query import QuerySet
from django.contrib import messages
from django.shortcuts import render, redirect
from django.views.generic.list import ListView
from django.core.mail import send_mail
from django.db.models import Q
from django.views.generic.edit import CreateView, UpdateView, DeletionMixin, DeleteView
from django.urls import reverse_lazy
from django.http import HttpResponseRedirect, request
from django.views.generic import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from store.models import OrderItem, Order
from accounts.models import User
from .forms import ProductForm, CategoriesForm, OrderUpdateForm
from .models import Product, Categories
from django.contrib.auth.decorators import user_passes_test

from mail.models import Email

# Create your views here.



#PRODUCTS VIEWS
class ProductView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    login_url = reverse_lazy('account_login')
    def test_func(self):
        return self.request.user.is_staff
    model = Product
    template_name = 'products/product_list.html'
    context_object_name = 'products'
    ordering = ['title']
    
class ProductCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    login_url = reverse_lazy('account_login')
    def test_func(self):
        return self.request.user.is_staff
    model = Product
    form_class = ProductForm
    template_name = 'products/product_create.html'
    success_url = reverse_lazy('products_list')

class ProductUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    login_url = reverse_lazy('account_login')
    def test_func(self):
        return self.request.user.is_staff
    model = Product
    template_name = 'products/product_update.html'
    form_class = ProductForm
    # success_url = reverse_lazy('products_list')
    context_object_name = 'products'
    object = Product.objects.all()
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category_context'] = Categories.objects.all()
        return context
    
    def get_success_url(self):
        
        if 'categories/' in self.request.path:
            the_pk = self.request.POST.get('product_category')
            category = Categories.objects.get(pk=the_pk)

            return reverse_lazy('product_by_category', kwargs={'category': category})
        else:
            return reverse_lazy('products_list')
    
    
    def form_valid(self, form):
        cleaned_stock = form.cleaned_data['stock']
        cleaned_id = form.cleaned_data['id_hidden']
        order_items = OrderItem.objects.filter(product=cleaned_id)
        for items in order_items:
            if items.quantity > cleaned_stock:
                items.quantity = cleaned_stock
                items.save()
        return super().form_valid(form)

   
        
        
class ProductDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    login_url = reverse_lazy('account_login')
    def test_func(self):
        return self.request.user.is_staff
    model = Product
    template_name = 'products/product_delete.html'
    success_url = reverse_lazy('products_list')

#CATEGORIES VIEWS

class CategoriesListView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    login_url = reverse_lazy('account_login')
    def test_func(self):
        return self.request.user.is_staff
    model = Categories
    template_name = 'products/category_list.html'
    context_object_name = 'categories'
    ordering = ['category_name']
    
    
class CategoriesCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    login_url = reverse_lazy('account_login')
    def test_func(self):
        return self.request.user.is_staff
    model = Categories
    template_name = 'products/category_create.html'
    form_class = CategoriesForm
    context_object_name = 'categories'
    success_url = reverse_lazy('category_list')
    
class CategoriesUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    login_url = reverse_lazy('account_login')
    def test_func(self):
        return self.request.user.is_staff
    model = Categories
    template_name = 'products/category_update.html'
    form_class = CategoriesForm
    context_object_name = 'categories'
    success_url = reverse_lazy('category_list')
    
class CategoriesDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    login_url = reverse_lazy('account_login')
    def test_func(self):
        return self.request.user.is_staff
    model = Categories
    template_name = 'products/category_delete.html'
    context_object_name = 'categories'
    success_url = reverse_lazy('category_list')
   
# SORTED PRODUCTS BY CATEGORY
class ProductsByCategoryView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    login_url = reverse_lazy('account_login')
    def test_func(self):
        return self.request.user.is_staff
    model = Product
    template_name = 'products/products_by_category.html'
    context_object_name = 'products'
    
    def get_queryset(self):
        return Product.objects.filter(product_category__category_name=self.kwargs['category'])
    

#ORDER MODELS
class OrdersIncompleteListView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    login_url = reverse_lazy('account_login')
    def test_func(self):
        return self.request.user.is_staff
    model = Order
    template_name = 'products/orders_incomplete_list.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['orders'] = Order.objects.filter(complete=False).order_by('-date_ordered')
        context['orders_count'] = Order.objects.filter(complete=False).count()


        return context
    
class OrdersCompleteListView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    login_url = reverse_lazy('account_login')
    def test_func(self):
        return self.request.user.is_staff
    model = Order
    template_name = 'products/orders_complete_list.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['orders'] = Order.objects.filter(complete=True).order_by('-date_ordered')
        context['orders_count'] = Order.objects.filter(complete=True).count()


        return context

class OrderItemsView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    login_url = reverse_lazy('account_login')
    def test_func(self):
        return self.request.user.is_staff
    model = OrderItem
    template_name = 'products/order_details.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['order'] = Order.objects.get(pk=self.kwargs['pk'])
        context['Items'] = OrderItem.objects.filter(order=self.kwargs['pk'])
        return context

class ProductDetailView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    login_url = reverse_lazy('account_login')
    def test_func(self):
        return self.request.user.is_staff
    model = OrderItem
    template_name = 'products/product_detail.html'
    context_object_name = 'order_item'


class OrderStatusChange(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    login_url = reverse_lazy('account_login')
    def test_func(self):
        return self.request.user.is_staff
    model = Order
    template_name = 'products/order_update.html'
    form_class = OrderUpdateForm
    context_object_name = 'order'
    success_url = reverse_lazy('orders_incomplete_list')
    
    def form_valid(self, form):
        instance = form.instance
        order = Order.objects.get(id=self.kwargs['pk'])
        if instance.complete == True:
            send_mail(
                'Order Update',
                'Your order has been processed and is now on the way to you!',
                'store@example.net',
                [order.customer.email],
               fail_silently = False,
            )
            form.save()
            return redirect(reverse_lazy('orders_incomplete_list'))
        else:
            messages.error(self.request, 'Form is invalid')
            form.save()
            return redirect(reverse_lazy('order_complete_list'))

    
   
        

class OrderUserDetailView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    login_url = reverse_lazy('account_login')
    def test_func(self):
        return self.request.user.is_staff
    model = User
    template_name = 'products/order_user_detail.html'
    context_object_name = 'user'
    
    
class CustomerOrderHistory(LoginRequiredMixin, UserPassesTestMixin, ListView):
    login_url = reverse_lazy('account_login')
    def test_func(self):
        return self.request.user.is_staff
    model = Order
    template_name = 'products/user_orders_list.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['orders'] = Order.objects.filter(customer=self.kwargs['pk'])
        return context
    

class ProductSearchView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    login_url = reverse_lazy('account_login')
    def test_func(self):
        return self.request.user.is_staff
    model = Product
    template_name = 'products/product_search_results.html'
    context_object_name = 'products'
    def get_queryset(self): 
        query = self.request.GET.get('q')
        return Product.objects.filter(
        Q(title__icontains=query) | Q(description__icontains=query)
        )
        
        
class OrderSearchView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    login_url = reverse_lazy('account_login')
    def test_func(self):
        return self.request.user.is_staff
    model = Order
    template_name = 'products/order_search_results.html'
    context_object_name = 'orders'
    def get_queryset(self): 
        query = self.request.GET.get('q')
        if query.isdigit():

django_project_root/products/templates/products/cant_use_word.html
{% extends '_base.html' %}

{% block title %}It worked{% endblock title %}

django_project_root/products/templates/products/failed_product_update.html
{% extends '_base.html' %}
{% load static %}

{% load crispy_forms_tags %}
{% block title %}Create Products{% endblock title %}
{% block extralink %}<link rel="stylesheet" href="{% static 'css/form.css' %}">{% endblock extralink %}
{% block content %}

<div class="form-box">
<form action="{% url 'product_update' products.pk %}" method="post">
    {% csrf_token %} 
    <div class="user-box">
        <select name="product_category">
            
        {% for cat in category_context %}
           <option {% if cat.id == preselect %} selected="selected" {% endif %} name="product_category" value="{{cat.id}}">{{ cat }}</option>
        {% endfor %}
        </select>
      </div>
      <div class="user-box">
        <input value="{{ form.title.value }}" type="text" name="title">
        <label>Title:</label>
      </div>
      <div class="user-box">
        <textarea name="description">{{ form.description.value }}</textarea>
        <label>Description:</label>
      </div>
      <div class="user-box">
        <input value="{{ form.price.value }}" type="number" name="price">
        <label>Price:</label>
      </div>
      <div class="user-box">
        <input value="{{ form.stock.value }}" type="number" name="stock">
        <label>Stock:</label>
      </div>
      <button type="submit" class="btn btn-primary btn-sm">
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        {{ category_context }}

    </button>


</form>



</div>


        

 
{% endblock content %}

django_project_root/products/templates/products/order_details.html
{% extends '_base.html' %}
{% load static %}

{% block title %}Order Details{% endblock title %}

{% block extralink %}<link rel="stylesheet" href="{% static 'css/store_css/product_detail.css' %}"> {% endblock extralink %}

{% block content %}
<div class="container">
    <div class="wrapper">    
    <h2>Order Id - {{ order.id }}</h2>
      <h2>Customer Email:</h2>
      <p><a href="{% url 'order_user_detail' order.customer.id %}">{{ order.customer }}</a></p>
      <h3 class="price">Address:</h3>
      <p>{{ order.address }}</p>
      <h3>Date Ordered:</h3>
      <p>{{ order.date_ordered }}</p>
      <h3>Notes:</h3>
      <p>{{ order.notes }}</p>
      <h2>Order Items</h2>
      {% for item in Items %}
      <h2><a href="{% url 'product_detail' item.id %}">{{ item.product.title }}</a></h2>

      {% endfor %}
     </div>
     
</div>



{% endblock content %}

django_project_root/products/templates/products/order_search_results.html
{% extends '_base.html' %}

{% block title %}Orders Search Results{% endblock title %}

{% block content %}
{% if orders %}

<div class="container">
    <h2>Search Results</h2>
    <form class="d-flex" action="{% url 'order_search_results' %}" method="get">
        <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-\
        label="Search" >
        <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
	<div>
	</div>
	<table>
		<thead>
			<tr>
				<th>Change order status</th>
				<th>Customer</th>
				<th>Items in Order</th>
				<th>View</th>
			</tr>
		</thead>
		<tbody>
            {% for order in orders %}

			<tr>
                <td><a href="{% url 'order_update' order.id %}">{{ order.id }}</a></td>
				<td>{{ order.customer }}</td>
				<td>{{ order.order_item_count }}</td>
				<td><a href="{% url 'order_items' order.id %}">View Order</a></td>
 
			</tr>
            {% endfor %}

			
		</tbody>
	</table>
</div>
{% else %}
<div class="container">
    <h1>Sorry, no orders matched your search</h1>
    <form class="d-flex" action="{% url 'order_search_results' %}" method="get">
        <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-\
        label="Search" >
        <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
</div>
{% endif %}
{% endblock content %}

django_project_root/products/templates/products/order_update.html
{% extends '_base.html' %}
{% load static %}

{% load crispy_forms_tags %}
{% block title %}Create Products{% endblock title %}

{% block content %}


<div class="form-container">
<form action="" method="POST">
    {% csrf_token %}
    {{ form|crispy}} 
    <button type="submit" class="btn btn-primary btn-sm">Submit</button>
    <div class="annoying">
    <button class="Delete"><a href="{% url 'orders_incomplete_list' %}" class="delete_product">Cancel</a></button>
    </div>
</form> 
</div>


 
{% endblock content %}

django_project_root/products/templates/products/order_user_detail.html
{% extends '_base.html' %}
{% load static %}

{% block title %}User Details{% endblock title %}

{% block extralink %}<link rel="stylesheet" href="{% static 'css/store_css/product_detail.css' %}"> {% endblock extralink %}

{% block content %}
<div class="container">
    <div class="wrapper">
        <img src="{{ user.imageURL }}" alt="">    
    <h2>Customer Id - {{ user.id }}</h2>
      <h2>Customer Email:</h2>
      <p>{{ user }}</p>
      <h3 class="price">Username </h3>
      <p>{{ user.username }}</p>
      <button type="submit" class="btn btn-primary btn-sm"><a href="{% url 'user_order_history' user.id %}">Order History</a></button>

      
     </div>
     
</div>



{% endblock content %}

django_project_root/products/templates/products/orders_complete_list.html
{% extends '_base.html' %}

{% block title %}Orders{% endblock title %}

{% block content %}
{% if orders %}

<div class="container">
	<h1>Complete Orders: {{ orders_count }}</h1>
	<form class="d-flex" action="{% url 'order_search_results' %}" method="get">
        <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-\
        label="Search" >
        <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
	<div>
	</div>
	<table>
		<thead>
			<tr>
				<th>Change order status</th>
				<th>Customer</th>
				<th>Items in Order</th>
				<th>View</th>
			</tr>
		</thead>
		<tbody>
            {% for order in orders %}

			<tr>
                <td><a href="{% url 'order_update' order.id %}">{{ order.id }}</a></td>
				<td>{{ order.customer }}</td>
				<td>{{ order.order_item_count }}</td>
				<td><a href="{% url 'order_items' order.id %}">View Order</a></td>
 
			</tr>
            {% endfor %}

			
		</tbody>
	</table>
</div>
{% else %}
<h1>nothing here</h1>
{% endif %}
{% endblock content %}

django_project_root/products/templates/products/product_create.html
{% extends '_base.html' %}
{% load static %}

{% load crispy_forms_tags %}
{% block title %}Create Products{% endblock title %}

{% block content %}

<div class="form-container">
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %} 
        {{ form|crispy}} 
        <button type="submit" class="btn btn-primary btn-sm">Submit</button>
        <div class="annoying">                         
        </div>
    </form> 
    </div>
{% endblock content %}

django_project_root/products/templates/products/product_delete.html
{% extends '_base.html' %}

{% load crispy_forms_tags %}
{% block title %}Delete Product{% endblock title %}

{% block content %}

<div class="form-container">
    <h3>{{ "Please Confirm Deletion"|title }}</h3>
    <form action="" method="POST">
        {% csrf_token %} 
        {{ form|crispy}} 
        <button type="submit" class="btn btn-primary btn-sm">Confirm</button>
    </form> 
    </div>

{% endblock content %}

django_project_root/products/templates/products/product_detail.html
{% extends '_base.html' %}
{% load static %}

{% block title %}{{ order_item.product.title|title }} Details{% endblock title %}

{% block extralink %}<link rel="stylesheet" href="{% static 'css/store_css/product_detail.css' %}"> {% endblock extralink %}

{% block content %}
<div class="container">
    <div class="wrapper">    
        <h1> {{ order_item.product.title }}</h1>
        <img src="{{ order_item.product.imageURL }}" class="banner-image">          
        <h3 class="price">Price: ${{ order_item.product.price }}</h3>
        <h3>Quantity Requested: {{ order_item.quantity }}</h3>
        <h3>Customer notes:</h3>
        <h2>{{ order_item.notes }}</h2>
        <h3></h3>
       </div>
     </div>
     
</div>



{% endblock content %}

django_project_root/products/templates/products/product_list_empty.html
<div class="logout-page">
    <h2>Uh oh, it appears you don't have any products yet...</h2>
        <button class='glowing-btn' id="logout-button"><a href="{% url 'product_create' %}"><span class='glowing-txt'>A<span class='faulty-letter'>D</span>D</span></a></button>
</div>

django_project_root/products/templates/products/product_search_results.html
{% extends '_base.html' %}
{% load static %}
{% block title %}Product Search Results{% endblock title %}

{% block content %}
{% if products %}
<div class="container">
	<h1>{{"These are you products, click on the title to edit any products you wish!"|title}}</h1>
	<div>
		<a href="{% url 'product_create' %}">Add Product</a>
		<form class="d-flex" action="{% url 'product_search_results' %}" method="get">
			<input class="form-control me-2" type="search" name="q" placeholder="Search" aria-\
			label="Search" >
			<button class="btn btn-outline-success" type="submit">Search</button>
		</form>
	</div>
	<table>
		<thead>
			<tr>
				<th>Title</th>
				<th>Description</th>
				<th>Price</th>
				<th>Stock</th>
				<th>Category</th>
			</tr>
		</thead>
		<tbody>
            {% for product in products %}

			<tr>
				<td><a href="{% url 'product_update' product.id %}">{{ product.title }}</a></td>
				<td>{{ product.description|truncatechars:50|capfirst }}</td>
				<td>{{ product.price }}</td>
				<td>{{ product.stock }}</td>
				<td>{{ product.product_category }}</td>
			</tr>
            {% endfor %}

			
		</tbody>
	</table>
</div>
{% else %}
<div class="container">
	<h1>{{"Sorry, No products matched your search"|title}}</h1>
	<div>
		<form class="d-flex" action="{% url 'product_search_results' %}" method="get">
			<input class="form-control me-2" type="search" name="q" placeholder="Search" aria-\
			label="Search" >
			<button class="btn btn-outline-success" type="submit">Search</button>
		</form>
	</div>
</div>
{% endif %}
{% endblock content %}

django_project_root/products/templates/products/product_update.html
{% extends '_base.html' %}
{% load static %}

{% load crispy_forms_tags %}
{% block title %}Edit Product{% endblock title %}

{% block content %}


<div class="form-container">
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy}} 
    <input type="hidden" name="id_hidden" value="{{ products.id }}" id="id_id_hidden">
    <button type="submit" class="btn btn-primary btn-sm">Submit</button>
    <div class="annoying">
    <button class="Delete"><a href="{% url 'product_delete' products.id %}" class="delete_product">Or Delete</a></button>
    </div>
</form> 
</div>


 
{% endblock content %}

django_project_root/products/templates/products/products_by_category.html
{% extends '_base.html' %}

{% block title %}Products in Category{% endblock title %}

{% block content %}
<div class="container">
	<div>
	</div>
	{% for product in products %}
		{% if forloop.first %}
			<h2><b>{{ product.product_category }}</b> Category Products</h2>
		{% endif %}
	{% endfor %}
	<table>
		<thead>
			<tr>
				<th>Title</th>
				<th>Description</th>
				<th>Price</th>
				<th>Stock</th>
				<th>Created On</th>
			</tr>
		</thead>
		<tbody>
            {% for product in products %}
               
                <tr>
                    <td><a href="{% url 'products_by_cat_up' product.id %}">{{ product.title|title }}</a></td>
					<td>{{ product.description|truncatechars:50 }}</td>
					<td>{{ product.price }}</td>
					<td>{{ product.stock }}</td>
					<td>{{ product.created_at }}</td>
                </tr>
             
            {% endfor %}

			
		</tbody>
	</table>
</div>

{% endblock content %}