django_project_root/django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('products/', include('products.urls')),
    path('accounts/', include('allauth.urls')),
    path('store/', include('store.urls')),
    path('emails/', include('mail.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_project_root/mail/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('', EmailListView.as_view(), name='email_list'),
    path('update/<slug:pk>/', EmailUpdateView.as_view(), name='email_update'),
    path('create/', EmailCreateView.as_view(), name='create_email'),
    path('details/<slug:pk>/', EmailDetailView.as_view(), name='email_details'),
    path('email/confirm/send/<slug:pk>/', EmailConfirmSendView.as_view(), name='email_send_confirm'),
    path('email/delete/<slug:pk>/', EmailDeleteView.as_view(), name='delete_email'),
]

django_project_root/store/urls.py
from django.urls import path
from allauth.account.views import SignupView, LoginView, LogoutView
from .views import *

urlpatterns = [
    path('', StoreFrontView.as_view(), name='storefront'),
    path('product/<slug:product_id>/', ProductCreateView.as_view(), name='product_detail_store'),
    path('products/', StoreAllProductsView.as_view(), name='all_products'),
    path('cart/', CartView.as_view(), name='cart'),
    path('cart/delete/<slug:pk>/', DeleteCartItemView.as_view(), name='delete_cart_item'),
    path('cart/checkout/', CheckoutView.as_view(), name='checkout'),
    path('cart/checkout/success', CheckoutSuccess.as_view(), name='checkout_success'),
    path('customer/signup/', SignupView.as_view(template_name='store/account/signup.html'), name='store_signup'),
    path('customer/login/', LoginView.as_view(template_name='store/account/login.html'), name='store_login'),
    path('customer/logout/', LogoutView.as_view(template_name='store/account/logout.html'), {'next_page': 'profile', }, name='store_logout'),
    path('profile/', CustomerProfileView.as_view(), name='profile'),
    path('profile/order/history/', CustomerOrderHistoryView.as_view(), name='customer_order_history'),
    path('profile/order/history/<slug:pk>/', CustomerOrderHistoryDetailView.as_view(), name='order_history_detail'),
    path('search/', ProductsSearchResults.as_view(), name='store_search_results'),
    path('categories/', CategoriesListView.as_view(), name='store_categories_list'),
    path('categories/<slug:pk>/', ProductsByCategoryView.as_view(), name='products_by_category'),
    path('contact/', ContactStoreView.as_view(), name='store_contact'),
    path('contact/success/', ContactStoreSuccessView.as_view(), name='contact_success'),

]

django_project_root/store/models.py
from django.db import models

from datetime import datetime
from products.models import Product
from accounts.models import User

# Create your models here.





class Order(models.Model):
    BOOL_CHOICES = ((True, 'Complete'), (False, 'Incomplete'))

    customer = models.ForeignKey(User, on_delete=models.CASCADE)
    id = models.AutoField(primary_key=True)
    address = models.CharField(max_length=200, null=True)
    notes = models.TextField(max_length=300, null=True)
    date_ordered = models.DateTimeField(auto_now_add=True, null=True)
    complete = models.BooleanField(default=False, null=True, blank=True, choices=BOOL_CHOICES)
 
    def __str__(self):
        return f"{self.id}"
    
    @property
    def order_item_count(self):
        return OrderItem.objects.filter(order=self.id).count()
    
    
class OrderItem(models.Model):

    customer = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, blank=True, null=True, related_name='order_items')
    date_added = models.DateTimeField(auto_now_add=True)
    useless = models.IntegerField(blank=True, null=True, default=0)
    id = models.AutoField(primary_key=True)
    added_to_order = models.BooleanField(default=False, null=True, blank=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    filter_item = models.IntegerField(default=0, null=True, blank=True)
    
    def __str__(self):
        return str(self.id)
    
    @property
    def order_item_price(self):
        var = self.quantity * self.product.price
        return var 





# class OrderItemTracker(models.Model):
#     user = models.ForeignKey(User, on_delete=models.CASCADE)
#     date_ordered = models.DateTimeField(auto_now_add=True)
#     complete = models.BooleanField(default=False, null=True, blank=True)
#     order_item = models.ForeignKey(OrderItem, on_delete=models.CASCADE, null=True, blank=True)
#     quantity = models.IntegerField(default=0, null=True, blank=True)
#     filter_item = models.IntegerField(default=0, null=True, blank=True)
#     id = models.AutoField(primary_key=True)
#     order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)

    
    
#     def __str__(self):
#         return str(self.id)

    
#     @property
#     def order_item_price(self):
#         var = self.quantity * self.order_item.product.price
#         return var 
#     @property
#     def cart_total(self):
        
#         var1 = OrderItemTracker.objects.all()[0].order_item_price
#         return f"{var1}"
    
    

        

django_project_root/store/forms.py
from django import forms
from django.forms import HiddenInput, NumberInput
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse, HttpResponseRedirect
from .models import OrderItem, Order
from accounts.models import User
from django.contrib import messages


class OrderItemForm(forms.ModelForm):
    class Meta:
        model = OrderItem
        fields = ['useless', 'quantity', 'filter_item']
        widgets = {'useless': HiddenInput(), 'filter_item': HiddenInput(), 'quantity': NumberInput(attrs={'class': 'numberinput',})}
        
    
class OrderItemDeleteForm(forms.ModelForm):
    class Meta:
        model = OrderItem
        fields = '__all__'


# class OrderItemTrackerForm(forms.ModelForm):
#     class Meta:
#         model = OrderItemTracker
#         fields = ['quantity',]
     
        
# class OrderItemTrackerUpdateForm(forms.ModelForm):
#     class Meta:
#         model = OrderItemTracker
#         fields = ['quantity', 'filter_item']
#         widgets = {'filter_item': HiddenInput(),}
        

class OrderCheckoutForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['address', 'notes']
      
        
# class CheckoutOrderTracker(forms.ModelForm):
#     class Meta:
#         model = OrderItemTracker
#         fields = ['complete', ]
#         widgets = {'complete': HiddenInput(),}
   
class UserImageForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['profile_img', ]
        
        
class ContactStoreForm(forms.Form):
    subject = forms.CharField()
    body = forms.CharField(widget=forms.Textarea(attrs={'class': 'body-in'}))
    
    def __init__(self, *args, **kwargs):
        if kwargs.get('user'):
            self.user = kwargs.pop('user', None)
        super(ContactStoreForm, self).__init__(*args,**kwargs)
        
    def send_email(self):
        subject = self.cleaned_data['subject']
        message = self.cleaned_data['body']
        from_email = self.user.email
        admin = User.objects.filter(is_superuser=True).first()
        if subject and message and from_email:
            send_mail(subject, message, from_email, [admin])
          

django_project_root/store/views.py
from typing import Any, Dict
from django.db.models.query import QuerySet
from django.forms.models import BaseModelForm
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView, CreateView, FormView, DeleteView
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from products.models import Product, Categories
from .models import OrderItem, Order
from django.core.mail import send_mail
from django.db.models import Q

from accounts.models import User
from .forms import *
from django import forms
from django.db.models import F, Sum

# Create your views here.

class StoreFrontView(ListView):
    template_name = 'store/storefront.html'
    model = Product
    def get_context_data(self, **kwargs):
        context = super(StoreFrontView, self).get_context_data(**kwargs)
        context['products'] = Product.objects.filter(display_product=True).order_by('-created_at')[:6]
        return context
    

class StoreAllProductsView(ListView):
    template_name = 'store/all_products.html'
    model = Product
    def get_context_data(self, **kwargs):
        context = super(StoreAllProductsView, self).get_context_data(**kwargs)
        context['products'] = Product.objects.filter(display_product=True).order_by('title')
        return context


class ProductCreateView(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('profile')
    template_name = 'store/product_detail.html'
    model = OrderItem
    form_class = OrderItemForm
    # quantity_form_class = OrderItemTrackerForm
    def get_success_url(self):
        return self.request.path
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # quantity_form = self.quantity_form_class(prefix='quantity_form')

        # context['quantity_form'] = quantity_form
        context['OrderItem'] = OrderItem.objects.all()
        context['product'] = Product.objects.get(id=self.kwargs['product_id'])
        context['amount_requested'] = OrderItem.objects.filter(product = self.kwargs['product_id'], customer=self.request.user, added_to_order=False).first()
        
        return context
    
    # def form_valid(self, form):
    #     form.instance.product_id = self.kwargs['product_id']
    #     # form.instance.user = self.request.user
    #     return super().form_valid(form)    
    
    # def get(self, request, *args, **kwargs):
    #     form = self.form_class(**self.get_form_kwargs())
    #     quantity_form = self.quantity_form_class(prefix='quantity_form')
    #     return render(request, self.template_name, {'form': form, 'quantity_form': quantity_form})
    
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        # quantity_form = self.quantity_form_class(request.POST, prefix='quantity_form')
        form.instance.product_id = self.kwargs['product_id']
       
        if form.is_valid():
            if OrderItem.objects.filter(product = self.kwargs['product_id'], customer=request.user, added_to_order=False).exists():
                orderitem = OrderItem.objects.get(product = self.kwargs['product_id'], customer=request.user, added_to_order=False)

                # myitem = OrderItem.objects.get(product = self.kwargs['product_id'], customer=request.user, id=orderitem.id)
                # raise forms.ValidationError(('This crap dont work'), code='invalid')
                # thetracker = OrderItemTracker.objects.get(order_item = myitem)
                # orderitem = OrderItemTracker.objects.get(order_item=myitem, user=request.user)
                cleaned_quantity = form.instance.quantity
                if cleaned_quantity > orderitem.product.stock:
                    messages.error(request, 'Sorry, please select an amount within the available stock')
                    
                elif (cleaned_quantity + orderitem.quantity) > orderitem.product.stock: 
                    messages.error(request, 'Sorry, you have already requested the maximum amount available')
                
                elif cleaned_quantity <= 0:
                    messages.error(request, f'Sorry, please select a quantity greater than 0')
                    
                else:
                    OrderItem.objects.filter(product = orderitem.product, customer=request.user, added_to_order=False).update(quantity=F('quantity')+cleaned_quantity)
                # quantity_form.instance.order_item = OrderItem.objects.get(id=myitem.pk)
                # quantity_form.save()   
            else:
                myitem = Product.objects.get(id=self.kwargs['product_id'])
                cleaned_quantity = form.instance.quantity
                
                if cleaned_quantity > myitem.stock: 
                    messages.error(request, 'Sorry, that exceeds the current stock of this item')
                elif cleaned_quantity <= 0:
                    messages.error(request, f'Sorry, please select a quantity greater than 0')
                else:
                    form.instance.product = Product.objects.get(id=myitem.id)
                    form.instance.customer = request.user
                    
                    form.save()   

            return redirect(self.request.path)

# class CartView(ListView):
#     template_name = 'store/cart.html' 
#     model = OrderItemTracker
#     context_object_name = 'Items'
    
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['Items'] = OrderItemTracker.objects.all()
#         return context

class CartView(LoginRequiredMixin, FormView):
    login_url = reverse_lazy('profile')
    template_name = 'store/cart.html' 
    model = OrderItem
    context_object_name = 'Items'
    form_class = OrderItemForm
    
    #Queries and stuff
   
    
   
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        OrderItemTrackObject = OrderItem.objects.filter(customer=self.request.user, added_to_order=False)
        context['Items'] = OrderItemTrackObject
        context['form'] = OrderItemForm
        cart_total = 0
        for item in OrderItemTrackObject:
            cart_total += item.order_item_price
            
        context['cart_total'] = cart_total   
        
        return context
    
    
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
       
        if form.is_valid():
            
            filteritem = form.cleaned_data['filter_item'] 
            cleaned_quantity = form.instance.quantity
            
            amount = OrderItem.objects.get(id=filteritem, customer=request.user)
            
            if cleaned_quantity > amount.product.stock:
                messages.error(request, 'Sorry, that exceeds the current stock of this item')
            elif (cleaned_quantity) > amount.product.stock:
                messages.error(request, 'Sorry, you have already requested the maximum amount available')
            elif cleaned_quantity <= 0:
                messages.error(request, 'Sorry, please select a quantity greater than 0')
            else:
                OrderItem.objects.filter(id=filteritem, customer=request.user).update(quantity=cleaned_quantity)

           
        return redirect(self.request.path)
    
    
class DeleteCartItemView(LoginRequiredMixin, DeleteView):
    login_url = reverse_lazy('profile')
    template_name = 'store/delete_cart_item.html'
    model = OrderItem
    success_url = reverse_lazy('cart')
    
   
class CheckoutView(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('profile')
    template_name = 'store/checkout.html'
    model = Order
    form_class = OrderCheckoutForm
    
    def get_success_url(self):
        return self.request.path
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['Order'] = Order.objects.filter(customer=self.request.user)
        context['order_trackers'] = OrderItem.objects.filter(customer=self.request.user, added_to_order=False)

        return context
    
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)        
        if form.is_valid():
            form.instance.customer = request.user

            n = form.save()
            
            myitems = OrderItem.objects.filter(customer=request.user, added_to_order=False)
            order = Order.objects.get(id=n.pk)
            for item in myitems:
                item.order = order
                item.added_to_order = True
                item.product.stock = (item.product.stock - item.quantity)
                item.product.save()
                item.save()
            send_mail(
                'Order Success',
                f'You have successfully placed your order with the id number {order.id}',
                'Store@example.net',
               [order.customer],
               fail_silently = False,
            )
        return redirect(request.path)
    
class CheckoutSuccess(LoginRequiredMixin, TemplateView):
    login_url = reverse_lazy('profile')
    template_name = 'store/checkout_success.html'
    
    
class CustomerProfileView(TemplateView):
    template_name = 'store/profile.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            context['Orders'] = Order.objects.filter(customer=self.request.user).count()

        return context
   
    
    
class CustomerOrderHistoryView(LoginRequiredMixin, ListView):
    login_url = reverse_lazy('profile')

django_project_root/store/templates/store/all_products.html
{% extends 'store/storefront.html' %}
{% load static %}

{% block title %}All Products{% endblock title %}

{% block content %}
<section class="product_section layout_padding">
    <div class="container">
       <div class="heading_container heading_center">
          <h2>
             Our <span>products</span>
          </h2>
       </div>
       <div class="row">
         {% for product in products %}

          <div class="col-sm-6 col-md-4 col-lg-4">
             <div class="box">
                <div class="option_container">
                   <div class="options">
                      <a href="{% url 'product_detail_store' product.id %}" class="option1">
                      View Product
                      </a>
                     
                   </div>
                </div>
                <div class="img-box">
                   <img src="{{ product.imageURL }}" alt="">
                </div>
                <div class="detail-box">
                   <h5>
                      {{ product.title|title }}
                   </h5>
                   <h6>
                      ${{ product.price}}
                   </h6>
                </div>
                {{ product.stock_amount }}
             </div>
          </div>    
          {% endfor %}

       </div>

       
       </div>
    </div>
 </section>

{% endblock content %}

django_project_root/store/templates/store/cart.html
{% extends 'store/storefront.html' %}
{% load static %}

{% block title %}Cart{% endblock title %}

{% block extralink %}<link rel="stylesheet" href="{% static 'css/store_css/cart.css' %}">{% endblock extralink %}

{% block content %}
                                              
{% if Items %}
<section class="shopping-cart dark">
    <div class="container">
       <div class="block-heading">
         <h2>Shopping Cart</h2>
         <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc quam urna, dignissim nec auctor in, mattis vitae leo.</p>
       </div>
       <div class="content">
            <div class="row">
                <div class="col-md-12 col-lg-8">
                    <div class="items">
                       
                        {% for item in Items %}
                        <div class="product">
                            <div class="row">
                                <div class="col-md-3">
                                   
                                    <img class="img-fluid mx-auto d-block image" src="{{ item.product.imageURL}}">
                                </div>
                                <div class="col-md-8">
                                    <div class="info">
                                        <div class="row">
                                            <div class="col-md-5 product-name">
                                                <div class="product-name">
                                                    <a href="#">{{ item.product.title }}</a>
                                                    <div class="product-info">
                                                        <div>Description: <span class="value">{{ item.product.description|truncatewords:20 }}</span></div>
                                                        <div>Price: <span class="value">{{ item.product.price }}</span></div>
                                                        <div>Quantity: <span class="value">{{ item.quantity }}</span></div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="col-md-4 quantity">
                                                <h3>Amount in stock: {{ item.product.stock }}</h3>
                                                
                                                <label for="quantity">Quantity:</label>
                                                <form action="" method="post">
                                                    {% csrf_token %}
                                                    <input type="number" name="quantity" value="{{ item.quantity}}" id="id_quantity">
                                                    <input type="hidden" name="filter_item" value="{{ item.id }}">
                                                    <button type="submit">Need to make this look good</button>
                                                </form>
                                            </div>
                                            <div class="col-md-3 price">
                                                
                                                <span>${{ item.order_item_price }}</span>
                                                <span><a href="{% url 'delete_cart_item' item.id %}">Remove from cart</a></span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
                <div class="col-md-12 col-lg-4">
                    <div class="summary">
                        <h3>Summary</h3>
                        {% comment %}
                        <div class="summary-item"><span class="text">Subtotal</span><span class="price"></span></div>
                        <div class="summary-item"><span class="text">Discount</span><span class="price">$0</span></div>
                        <div class="summary-item"><span class="text">Shipping</span><span class="price">$0</span></div>
                        {% endcomment %}
                        <div class="summary-item"><span class="text">Total</span><span class="price">${{ cart_total}}</span></div>
                        <a class="checkout-button" href="{% url 'checkout' %}"><button type="button" class="btn btn-primary btn-lg btn-block">Checkout</button></a>
                        {% if messages %}
                        {% for message in messages %}
                            {{ message }}
                        {% endfor %}
                    {% endif %}
                    </div>
                </div>
            </div> 
        </div>
    </div>
</section>
{% else %}
<section class="shopping-cart dark">
    <div class="container">
       <div class="block-heading">
         <h2>Shopping Cart</h2>
         <p>There doesn't appear to be any items in your cart:/</p>
       </div>
       <div class="content">
            
    </div>
    </div>
</section>
{% endif %}

{% endblock content %}

django_project_root/store/templates/store/categories_list.html
{% extends 'store/storefront.html' %}
{% load static %}

{% block title %}Categories{% endblock title %}

{% block extralink %} <link rel="stylesheet" href="{% static 'css/store_css/categories.css' %}"> {% endblock extralink %}

{% block content %}
<section class="product_section layout_padding">
    <div class="container">
       <div class="heading_container heading_center">
          <h2>
             Our <span>Categories</span>
          </h2>
       </div>
       
       <ol style="--length: 5" role="list">
        {% for category in categories %}
        <li style="--i: 1"  class="listitem">
          <h3><a href="{% url 'products_by_category' category.id %}">{{ category.category_name }}</a></h3>
          <p>{{ category.description }}</p>
        </li>
        {% endfor %}
        
      </ol>
    
      

       
       </div>
    </div>
 </section>

{% endblock content %}

django_project_root/store/templates/store/checkout.html
{% extends 'store/storefront.html' %}
{% load static %}

{% block title %}Checkout{% endblock title %}
{% block extralink %} <link rel="stylesheet" href="{% static 'css/store_css/product_detail.css' %}"> {% endblock extralink %}

{% block content %}
{% if order_trackers %}
<div class="container">
    <div class="wrapper">  
    <h1>Checkout</h1>
  
      <form action="" method="post"> 
         {% csrf_token %}
         {{ form }}
         
         <button class="btn outline" type="submit">Checkout</button>
         {% for orders in order_trackers %}
         <input type="hidden" name="id" value="{{ order_trackers.id }}">
         {% endfor %}
      </form>
      <button class="btn outline"><a href="{% url 'cart' %}">Cancel</a></button>
     </div>
       </div>
   </div>
{% else %}
<div class="container">
    <div class="wrapper">  
    <h1>You currently do not have any items in your cart</h1>
      
     </div>
       </div>
{% endif %}
{% endblock content %}

django_project_root/store/templates/store/checkout_success.html
{% extends 'store/storefront.html' %}
{% load static %}

{% block title %}Checkout{% endblock title %}
{% block extralink %} <link rel="stylesheet" href="{% static 'css/store_css/product_detail.css' %}"> {% endblock extralink %}

{% block content %}
<div class="container">
    <div class="wrapper">  
    <h1>You currently do not have any items in your cart</h1>
      
     </div>
       </div>
{% endblock content %}

django_project_root/store/templates/store/contact.html
{% extends 'store/storefront.html' %}
{% load static %}

{% block title %}Checkout{% endblock title %}
{% block extralink %} <link rel="stylesheet" href="{% static 'css/store_css/contact.css' %}"> <link rel="stylesheet" href="{% static 'css/store_css/product_detail.css' %}"> {% endblock extralink %}

{% block content %}
<div class="container">
    <div class="wrapper">  
    <form action="" method="POST">
        {% csrf_token %}
        {{ form }}
        <button class="btn outline contact-bt" type="submit">Send</button>
    </form>
      
     </div>
       </div>
{% endblock content %}

django_project_root/store/templates/store/contact_success.html
{% extends 'store/storefront.html' %}
{% load static %}

{% block title %}Contact Success{% endblock title %}
{% block extralink %} <link rel="stylesheet" href="{% static 'css/store_css/product_detail.css' %}"> {% endblock extralink %}

{% block content %}
<div class="container">
    <div class="wrapper">  
    <h1>Thank you for your input! We will get back to you shortly</h1>
      
     </div>
       </div>
{% endblock content %}

django_project_root/store/templates/store/delete_cart_item.html
{% extends 'store/storefront.html' %}
{% load static %}

{% block title %}Remove Product{% endblock title %}
{% block extralink %} <link rel="stylesheet" href="{% static 'css/store_css/product_detail.css' %}"> {% endblock extralink %}

{% block content %}
<div class="container">
    <div class="wrapper">  
    <h1>Are you sure you want to delete{{ orderitems.product.title }}?</h1>
  
      <form action="" method="post"> 
         {% csrf_token %}
         {{ form }}
         <button class="btn outline" type="submit">Delete</button>
      </form>
      <button class="btn outline"><a href="{% url 'cart' %}">Cancel</a></button>
     </div>
       </div>
   </div>


{% endblock content %}

django_project_root/store/templates/store/product_detail.html
{% extends 'store/storefront.html' %}
{% load static %}

{% block title %}{{ product.title|title }}{% endblock title %}

{% block extralink %} <link rel="stylesheet" href="{% static 'css/store_css/product_detail.css' %}"> {% endblock extralink %}

{% block content %}
<div class="container">
    <div class="wrapper">    
    <h1> {{ product.title }}</h1>
      <img src="{{ product.imageURL }}" class="banner-image">          
      <h3 class="price">Price: ${{ product.price }}</h3>
      <h3>Description:</h3>
      <h3>{{ product.description }}</h3>
     </div>
     {% if amount_requested %}
     <h4>You currently have <strong>{{ amount_requested.quantity }} </strong>of this {{ product.title }} in your cart </h4>

     {% endif %}
     <div class="button-wrapper">
      {% for message in messages %}
         {{ message }}
      {% endfor %}
      <form action="" method="post"> 
         {% csrf_token %}
         {{ form }}
         <button class="btn outline" type="submit">Add to Cart</button>
         {% comment %}
         <input type="hidden" name="id" value="{{ Order.id }}">
         {% endcomment %}
       

      </form>
     </div>
     <div class="stock">
     <h3>{{ product.stock_amount }}</h3>
    </div>
       </div>
   </div>
{% endblock content %}

django_project_root/store/templates/store/products_by_category.html
{% extends 'store/storefront.html' %}
{% load static %}

{% block title %}{{ Category.category_name }} Products{% endblock title %}

{% block content %}
<section class="product_section layout_padding">
    <div class="container">
       <div class="heading_container heading_center">
          <h2>
            {{ Category.category_name }} <span>products</span>
          </h2>
       </div>
       <div class="row">
         {% for product in products %}

          <div class="col-sm-6 col-md-4 col-lg-4">
             <div class="box">
                <div class="option_container">
                   <div class="options">
                      <a href="{% url 'product_detail_store' product.id %}" class="option1">
                      View Product
                      </a>
                     
                   </div>
                </div>
                <div class="img-box">
                   <img src="{{ product.imageURL }}" alt="">
                </div>
                <div class="detail-box">
                   <h5>
                      {{ product.title|title }}
                   </h5>
                   <h6>
                      ${{ product.price}}
                   </h6>
                </div>
                {{ product.stock_amount }}
             </div>
          </div>    
          {% endfor %}

       </div>

       
       </div>
    </div>
 </section>

{% endblock content %}